# Generated by Django 5.0.4 on 2024-04-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('is_euabel', models.BooleanField(default=False)),
                ('publish_data', models.DateField()),
                ('created_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
